# Generated by Django 2.0.2 on 2018-02-27 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('showlist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PalletList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pallet', models.CharField(default='Unknown', max_length=100)),
            ],
            options={
                'ordering': (),
            },
        ),
        migrations.RenameModel(
            old_name='List',
            new_name='CompanyList',
        ),
    ]
